__LINE__=__LINE__
__FILE__=__FILE__
__COUNTER__=__COUNTER__
__cplusplus=__cplusplus => 1
__LITTLE_ENDIAN__=__LITTLE_ENDIAN__ => 1
G_BYTE_ORDER=G_BYTE_ORDER => 1234
NDEBUG=NDEBUG => 1
__STDC__=__STDC__ => 1
HAVE_PROTOTYPES=HAVE_PROTOTYPES => 1
STDC_HEADERS=STDC_HEADERS => 1
_CHAR_UNSIGNED=_CHAR_UNSIGNED => 1
WIN32_LEAN_AND_MEAN=WIN32_LEAN_AND_MEAN => 1
_WCHAR_T_DEFINED=_WCHAR_T_DEFINED => 1
_NATIVE_WCHAR_T_DEFINED=_NATIVE_WCHAR_T_DEFINED => 1
_MSC_VER=_MSC_VER => 1100
WINAPI=WINAPI => __stdcall
TARGET_CPU_X86=TARGET_CPU_X86 => 1
__i386__=__i386__ => 1
M_I86=M_I86 => 1
_M_I86=_M_I86 => 1
_WIN32=_WIN32 => 1
__attribute__=__attribute__(x)
__OPENVR_API_FLAT_H__=__OPENVR_API_FLAT_H__
EXTERN_C=EXTERN_C => extern "C"
OPENVR_FNTABLE_CALLTYPE=OPENVR_FNTABLE_CALLTYPE => __stdcall
S_API=S_API => extern "C" __declspec( dllimport )
